<a href="https://colab.research.google.com/github/edilsonchaves/MVP-Machine-Learning-Analytics/blob/main/OscarResearchML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Descrição do Tabalho**

Neste trabalho busca fazer um levantamento sobre a maior premiação do oscar desde a sua primeira edição que ocorreu no ano de 1929 referente a filmes lançados nos anos de 1927/1928 até a edição de numero 97 que ocorreu no ano de 2026. Este trabalho é uma continuação do executado na sprint de analise de dados e boas práticas.
<br><br>

# **Coleta de dados**

Os dados foram coletados na plataforma kaggle no link : https://www.kaggle.com/datasets/unanimad/the-oscar-award e os dados brutos foram armazenados neste repositório git

# Imports

In [46]:
import requests
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

# Dados Brutos

In [47]:
url = "https://raw.githubusercontent.com/edilsonchaves/MVP-Machine-Learning-Analytics/refs/heads/main/full_data_2026.csv"
df = pd.read_csv(url, sep="\t")
display(df)

,Ceremony,Year,Class,CanonicalCategory,Category,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation
0,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Noose|The Patent Leather Kid,tt0019217|tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,NaN,Nickie Elkins|The Patent Leather Kid,NaN,NaN
1,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Last Command|The Way of All Flesh,tt0019071|tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexand...,NaN,NaN
2,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,NaN,Mrs. Pleznik,NaN,NaN
3,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,7th Heaven|Street Angel|Sunrise,tt0018379|tt0019429|tt0018455,Janet Gaynor,Janet Gaynor,nm0310980,True,Diane|Angela|The Wife,NaN,NaN
4,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,Sadie Thompson,tt0019344,Gloria Swanson,Gloria Swanson,nm0841797,NaN,Sadie Thompson,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12132,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Benjamin Graf,NaN,True,NaN,dxRevive Pro has transformed modern dialog res...,"To BENJAMIN GRAF for the design, engineering a..."
12133,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,John Ellwood|Jeff Bloom,NaN,True,NaN,Titan pioneered the auto-assembly of digital a...,To JOHN ELLWOOD for the innovative rules and h...
12134,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Marc Specter,NaN,True,NaN,With an intuitive user interface and transcrip...,To MARC SPECTER for the design and development...
12135,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Justin Webster,NaN,True,NaN,Providing detailed insight into differences be...,To JUSTIN WEBSTER for the design and engineeri...
12136,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Paul Debevec,NaN,True,NaN,Debevec demonstrated the advantages of high dy...,To PAUL DEBEVEC for his pioneering work in hig...

,Ceremony,Year,Class,CanonicalCategory,Category,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation
0,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Noose|The Patent Leather Kid,tt0019217|tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,NaN,Nickie Elkins|The Patent Leather Kid,NaN,NaN
1,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Last Command|The Way of All Flesh,tt0019071|tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexand...,NaN,NaN
2,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,NaN,Mrs. Pleznik,NaN,NaN
3,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,7th Heaven|Street Angel|Sunrise,tt0018379|tt0019429|tt0018455,Janet Gaynor,Janet Gaynor,nm0310980,True,Diane|Angela|The Wife,NaN,NaN
4,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,Sadie Thompson,tt0019344,Gloria Swanson,Gloria Swanson,nm0841797,NaN,Sadie Thompson,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12132,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Benjamin Graf,NaN,True,NaN,dxRevive Pro has transformed modern dialog res...,"To BENJAMIN GRAF for the design, engineering a..."
12133,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,John Ellwood|Jeff Bloom,NaN,True,NaN,Titan pioneered the auto-assembly of digital a...,To JOHN ELLWOOD for the innovative rules and h...
12134,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Marc Specter,NaN,True,NaN,With an intuitive user interface and transcrip...,To MARC SPECTER for the design and development...
12135,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Justin Webster,NaN,True,NaN,Providing detailed insight into differences be...,To JUSTIN WEBSTER for the design and engineeri...
12136,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Paul Debevec,NaN,True,NaN,Debevec demonstrated the advantages of high dy...,To PAUL DEBEVEC for his pioneering work in hig...

# **Pré Processamento**

Antes de inicializar as análises dos dados algumas modificação foram necessárias de serem realizadas para melhorar a qualidade dos dados

## Pré processamento Data Frame
A primeira etapa de pré processamento dos dados foi avaliar quais as colunas existentes na tabela para posteriormente poder escolher aquelas que mais poderiam ajudar nas respostas das questões. Por isso que das dezesseis colunas existentes apenas sete foram escolhidas sendo elas as

* Ceremony: Numero da cerimônia ao oscar
* Year: Ano de lançamento do filme que está sendo homenageado
* Canonical Category: Categoria da premiação
* Film: Nome do filme
* Name: texto preciso usado para quem estava sendo homenageado ou o país de origem em que o filme foi produzido na categoria de filme internacional
* Winner: Se a indicação terminou em vitória ou não
<br>
Além destas colunas foi necessário acrescentar mais 3 colunas

* Genre: Genero do Filme que foi Indicado ao oscar
* Birth Country: País de nascimento nos casos de categorias do oscar que homenageiam pessoas
* Birth Continent: Continente de nascimento nos casos de categorias do oscar que homenageiam pessoas

Na coluna de vencedores os valores 0 indica que a indicação não conquistou o prêmio e 1 é a indicação vencedora

In [48]:
df_Selected_Colluns = ["Ceremony", "Year", "Class", "CanonicalCategory", "Film", "Name", "Winner"]
df_With_Colluns = df[df_Selected_Colluns].copy()

In [49]:
df_With_Colluns["Winner"] = df_With_Colluns["Winner"].fillna(0)
df_With_Colluns["Winner"] = df_With_Colluns["Winner"].replace(True, 1)

/tmp/ipykernel_2618/1339843477.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_With_Colluns["Winner"] = df_With_Colluns["Winner"].replace(True, 1)
/tmp/ipykernel_2618/1339843477.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_With_Colluns["Winner"] = df_With_Colluns["Winner"].replace(True, 1)

In [50]:
display(df_With_Colluns)

,Ceremony,Year,Class,CanonicalCategory,Film,Name,Winner
0,1,1927/28,Acting,ACTOR IN A LEADING ROLE,The Noose|The Patent Leather Kid,Richard Barthelmess,0
1,1,1927/28,Acting,ACTOR IN A LEADING ROLE,The Last Command|The Way of All Flesh,Emil Jannings,1
2,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,A Ship Comes In,Louise Dresser,0
3,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,7th Heaven|Street Angel|Sunrise,Janet Gaynor,1
4,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,Sadie Thompson,Gloria Swanson,0
...,...,...,...,...,...,...,...
12132,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1
12133,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1
12134,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1
12135,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1
12136,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1

,Ceremony,Year,Class,CanonicalCategory,Film,Name,Winner
0,1,1927/28,Acting,ACTOR IN A LEADING ROLE,The Noose|The Patent Leather Kid,Richard Barthelmess,0
1,1,1927/28,Acting,ACTOR IN A LEADING ROLE,The Last Command|The Way of All Flesh,Emil Jannings,1
2,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,A Ship Comes In,Louise Dresser,0
3,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,7th Heaven|Street Angel|Sunrise,Janet Gaynor,1
4,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,Sadie Thompson,Gloria Swanson,0
...,...,...,...,...,...,...,...
12132,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1
12133,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1
12134,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1
12135,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1
12136,98,2025,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,1

## **Pré Processamento dos Dados**

Posteriormente que foi trabalhado consistiu em avaliar quais as Categorias de premiação do Oscar seriam trabalhadas para isso foram escolhidas 2 categorias no contexto de filmes sendo estas

* Melhor Filme
* Melhor Filme Internacional

Além de quatro no contexto de premiações para pessoas que foram

* Melhor Ator Principal tanto para Ator como Atriz
* Melhor Ator Coadjuvante tanto para Ator como Atriz
* Melhor Direção
* Melhor Roteiro Adaptado ou Original.

In [51]:
df_Selected_Categorys = ["BEST PICTURE",
                          "INTERNATIONAL FEATURE FILM",
                          "DIRECTING",
                          "ACTOR IN A LEADING ROLE",
                          "ACTRESS IN A LEADING ROLE",
                          "ACTOR IN A SUPPORTING ROLE",
                          "ACTRESS IN A SUPPORTING ROLE",
                          "WRITING (Adapted Screenplay)",
                          "WRITING (Original Story)",
                          #"MUSIC (Original Song)",
                          #"MUSIC (Original Score)",
                          #"VISUAL EFFECTS",
                          #"ART DIRECTION",
                          #"SOUND MIXING",
                          #"COSTUME DESIGN"
                          ]
df_Category_Research = df_With_Colluns[df_With_Colluns["CanonicalCategory"].isin(df_Selected_Categorys)]

## Resultado
Tais pre processamentos reduziu a amostragem para 6186 entradas e 7 colunas como mostrado no diplay abaixo

In [68]:
df_Official = df_Category_Research.copy()
display(df_Official)

,Ceremony,Year,Class,CanonicalCategory,Film,Name,Winner
0,1,1927/28,Acting,ACTOR IN A LEADING ROLE,The Noose|The Patent Leather Kid,Richard Barthelmess,0
1,1,1927/28,Acting,ACTOR IN A LEADING ROLE,The Last Command|The Way of All Flesh,Emil Jannings,1
2,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,A Ship Comes In,Louise Dresser,0
3,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,7th Heaven|Street Angel|Sunrise,Janet Gaynor,1
4,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,Sadie Thompson,Gloria Swanson,0
...,...,...,...,...,...,...,...
12108,98,2025,Writing,WRITING (Adapted Screenplay),Bugonia,Screenplay by Will Tracy,0
12109,98,2025,Writing,WRITING (Adapted Screenplay),Frankenstein,Written for the Screen by Guillermo del Toro,0
12110,98,2025,Writing,WRITING (Adapted Screenplay),Hamnet,Screenplay by Chloé Zhao & Maggie O'Farrell,0
12111,98,2025,Writing,WRITING (Adapted Screenplay),One Battle after Another,Written by Paul Thomas Anderson,1
12112,98,2025,Writing,WRITING (Adapted Screenplay),Train Dreams,Screenplay by Clint Bentley & Greg Kwedar,0

In [71]:
df_Official.isnull().sum()
df_Official[df_Official.isnull().any(axis=1)]

,Ceremony,Year,Class,CanonicalCategory,Film,Name,Winner
15,1,1927/28,Production,VISUAL EFFECTS,NaN,Ralph Hammeras,0
17,1,1927/28,Production,VISUAL EFFECTS,NaN,Nugent Slaughter,0
2616,23,1950,Title,INTERNATIONAL FEATURE FILM,The Walls of Malapaga,NaN,1
2738,24,1951,Title,INTERNATIONAL FEATURE FILM,Rashomon,NaN,1
2871,25,1952,Title,INTERNATIONAL FEATURE FILM,Forbidden Games,NaN,1
3139,27,1954,Title,INTERNATIONAL FEATURE FILM,Gate of Hell,NaN,1
3277,28,1955,Title,INTERNATIONAL FEATURE FILM,"Samurai, The Legend of Musashi",NaN,1

In [53]:
df_Official["Class"].unique()

array(['Acting', 'Production', 'Title', 'Writing', 'Directing', 'Music'],
      dtype=object)

array(['Acting', 'Production', 'Title', 'Writing', 'Directing', 'Music'],
      dtype=object)

In [54]:
df_Official.groupby("Class")["CanonicalCategory"].unique()

Class
Acting        [ACTOR IN A LEADING ROLE, ACTRESS IN A LEADING...
Directing                                           [DIRECTING]
Music           [MUSIC (Original Song), MUSIC (Original Score)]
Production    [ART DIRECTION, VISUAL EFFECTS, COSTUME DESIGN...
Title                [BEST PICTURE, INTERNATIONAL FEATURE FILM]
Writing       [WRITING (Adapted Screenplay), WRITING (Origin...
Name: CanonicalCategory, dtype: object

Class
Acting        [ACTOR IN A LEADING ROLE, ACTRESS IN A LEADING...
Directing                                           [DIRECTING]
Music           [MUSIC (Original Song), MUSIC (Original Score)]
Production    [ART DIRECTION, VISUAL EFFECTS, COSTUME DESIGN...
Title                [BEST PICTURE, INTERNATIONAL FEATURE FILM]
Writing       [WRITING (Adapted Screenplay), WRITING (Origin...
Name: CanonicalCategory, dtype: object

In [55]:
df_best_pictures_ML= df_Official.copy()
df_best_pictures_ML = (
    df_Official[df_Official["CanonicalCategory"] == "BEST PICTURE"]
    [["Film", "Year"]]
    .reset_index(drop=True)
)

#df_best_pictures_ML = pd.get_dummies(
#    df_best_pictures_ML,
#    columns=["Genre"],
#    prefix="Genre",
#    drop_first=True,
#    dtype=int
#)


for category in df_Selected_Categorys:
    df_best_pictures_ML[category] = 0

for category in df_Selected_Categorys:

    nominated_films = set(
        df_Official[
            df_Official["CanonicalCategory"] == category
        ]["Film"].dropna()
    )

    df_best_pictures_ML.loc[
        df_best_pictures_ML["Film"].isin(nominated_films),
        category
    ] = 1

total_nominations = (
    df_Official
    .groupby("Film")
    .size()
    .reset_index(name="Total_Nominations")
)

df_best_pictures_ML = df_best_pictures_ML.merge(
    total_nominations,
    on="Film",
    how="left"
)

winners = (
    df_Official[df_Official["CanonicalCategory"] == "BEST PICTURE"]
    [["Film", "Year", "Winner"]]
    .drop_duplicates()
)

df_best_pictures_ML = df_best_pictures_ML.merge(
    winners,
    on=["Film", "Year"],
    how="left"
)

display(df_best_pictures_ML)

,Film,Year,BEST PICTURE,INTERNATIONAL FEATURE FILM,DIRECTING,ACTOR IN A LEADING ROLE,ACTRESS IN A LEADING ROLE,ACTOR IN A SUPPORTING ROLE,ACTRESS IN A SUPPORTING ROLE,WRITING (Adapted Screenplay),WRITING (Original Story),MUSIC (Original Song),MUSIC (Original Score),VISUAL EFFECTS,ART DIRECTION,SOUND MIXING,COSTUME DESIGN,Total_Nominations,Winner
0,The Racket,1927/28,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,7th Heaven,1927/28,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,3,0
2,Wings,1927/28,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,1
3,Alibi,1928/29,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2,0
4,In Old Arizona,1928/29,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,One Battle after Another,2025,1,0,1,1,0,1,1,1,0,0,1,0,1,1,0,10,1
617,The Secret Agent,2025,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,3,0
618,Sentimental Value,2025,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,7,0
619,Sinners,2025,1,0,1,1,0,1,1,0,0,1,1,1,1,1,1,11,0
620,Train Dreams,2025,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,3,0

,Film,Year,BEST PICTURE,INTERNATIONAL FEATURE FILM,DIRECTING,ACTOR IN A LEADING ROLE,ACTRESS IN A LEADING ROLE,ACTOR IN A SUPPORTING ROLE,ACTRESS IN A SUPPORTING ROLE,WRITING (Adapted Screenplay),WRITING (Original Story),MUSIC (Original Song),MUSIC (Original Score),VISUAL EFFECTS,ART DIRECTION,SOUND MIXING,COSTUME DESIGN,Total_Nominations,Winner
0,The Racket,1927/28,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,7th Heaven,1927/28,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,3,0
2,Wings,1927/28,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,1
3,Alibi,1928/29,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2,0
4,In Old Arizona,1928/29,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,One Battle after Another,2025,1,0,1,1,0,1,1,1,0,0,1,0,1,1,0,10,1
617,The Secret Agent,2025,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,3,0
618,Sentimental Value,2025,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,7,0
619,Sinners,2025,1,0,1,1,0,1,1,0,0,1,1,1,1,1,1,11,0
620,Train Dreams,2025,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,3,0

In [56]:
df_best_pictures_ML["Year"] = (
    df_best_pictures_ML["Year"]
    .astype(str)
    .str[:4]
    .astype(int)
)

In [57]:
train_test_split_year = 2000
train_df = df_best_pictures_ML[df_best_pictures_ML["Year"] <= train_test_split_year]
test_df = df_best_pictures_ML[df_best_pictures_ML["Year"] > train_test_split_year]

In [58]:
x_train = train_df.drop(columns=["Film", "Winner", "Year"])
y_train = train_df["Winner"]

x_test = test_df.drop(columns=["Film", "Winner", "Year"])
y_test = test_df["Winner"]

In [59]:
def evaluate_model(modelName, model, X_train, X_test, Y_train, Y_test):
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  y_prob = model.predict_proba(X_test)[:, 1]

  acc = accuracy_score(Y_test, y_pred)
  f1 = f1_score(Y_test, y_pred)
  precision = precision_score(Y_test, y_pred)
  recall = recall_score(Y_test, y_pred)
  roc_auc = roc_auc_score(Y_test, y_pred)
  cm = confusion_matrix(Y_test, y_pred)
  tn, fp, fn, tp = cm.ravel()

  results = {
    "Model" : modelName,
    "Accuracy" : acc,
    "F1" : f1,
    "Precision" : precision,
    "Recall" : recall,
    "ROC AUC" : roc_auc,
    "True Negative" : tn,
    "False Positive" : fp,
    "False Negative" : fn,
    "True Positive" : tp
  }
  return results

In [60]:
trainning_basics_model = [
  {"name" : "Decision Tree Classifier", "Modelo" : DecisionTreeClassifier(random_state=42)},
  {"name" : "Random Forest Classifier", "Modelo" : RandomForestClassifier(random_state=42)},
  {"name" : "Logistic Regression", "Modelo" : LogisticRegression(random_state=42, max_iter=1000)},
  {"name" : "K Neighbors Classifier", "Modelo" : KNeighborsClassifier(n_neighbors=5)},
  {"name" : "SVC", "Modelo" : SVC(probability=True, random_state=42)}
]

all_basics_results = []
for model in trainning_basics_model:
  result = evaluate_model(model["name"], model["Modelo"], x_train, x_test, y_train, y_test)
  all_basics_results.append(result)

df_basics_result = pd.DataFrame(all_basics_results)
display(df_basics_result)

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,Decision Tree Classifier,0.811224,0.177778,0.200000,0.16,0.533216,155,16,21,4
1,Random Forest Classifier,0.785714,0.222222,0.206897,0.24,0.552749,148,23,19,6
2,Logistic Regression,0.795918,0.200000,0.200000,0.20,0.541520,151,20,20,5
3,K Neighbors Classifier,0.790816,0.196078,0.192308,0.20,0.538596,150,21,20,5
4,SVC,0.836735,0.157895,0.230769,0.12,0.530760,161,10,22,3

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,Decision Tree Classifier,0.811224,0.177778,0.200000,0.16,0.533216,155,16,21,4
1,Random Forest Classifier,0.785714,0.222222,0.206897,0.24,0.552749,148,23,19,6
2,Logistic Regression,0.795918,0.200000,0.200000,0.20,0.541520,151,20,20,5
3,K Neighbors Classifier,0.790816,0.196078,0.192308,0.20,0.538596,150,21,20,5
4,SVC,0.836735,0.157895,0.230769,0.12,0.530760,161,10,22,3

In [61]:
trainning_modify_model = [
  {"name" : "Decision Tree Classifier", "Modelo" : DecisionTreeClassifier(random_state=42, class_weight="balanced")},
  {"name" : "Random Forest Classifier", "Modelo" : RandomForestClassifier(random_state=42, class_weight="balanced")},
  {"name" : "Logistic Regression", "Modelo" : LogisticRegression(random_state=42, max_iter=1000, class_weight="balanced")},
  {"name" : "K Neighbors Classifier", "Modelo" : KNeighborsClassifier(n_neighbors=1)},
  {"name" : "SVC", "Modelo" : SVC(probability=True, random_state=42, class_weight="balanced")}
]

all_modify_results = []
for model in trainning_modify_model:
  result = evaluate_model(model["name"], model["Modelo"], x_train, x_test, y_train, y_test)
  all_modify_results.append(result)

df_modify_results = pd.DataFrame(all_modify_results)
display(df_modify_results)

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,Decision Tree Classifier,0.734694,0.187500,0.153846,0.24,0.523509,138,33,19,6
1,Random Forest Classifier,0.801020,0.264151,0.250000,0.28,0.578596,150,21,18,7
2,Logistic Regression,0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14
3,K Neighbors Classifier,0.811224,0.412698,0.342105,0.52,0.686901,146,25,12,13
4,SVC,0.658163,0.309278,0.208333,0.60,0.633333,114,57,10,15

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,Decision Tree Classifier,0.734694,0.187500,0.153846,0.24,0.523509,138,33,19,6
1,Random Forest Classifier,0.801020,0.264151,0.250000,0.28,0.578596,150,21,18,7
2,Logistic Regression,0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14
3,K Neighbors Classifier,0.811224,0.412698,0.342105,0.52,0.686901,146,25,12,13
4,SVC,0.658163,0.309278,0.208333,0.60,0.633333,114,57,10,15

In [62]:
all_modify_results = []
for p in ["l1"]:
  method_name = "Regression Advanced", p
  modelAdvanced = LogisticRegression(penalty = p,solver="liblinear", random_state=42, max_iter=1000, class_weight="balanced")
  result = evaluate_model(method_name, modelAdvanced, x_train, x_test, y_train, y_test)
  all_modify_results.append(result)
df_modify_results = pd.DataFrame(all_modify_results)
display(df_modify_results)

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,"(Regression Advanced, l1)",0.612245,0.269231,0.177215,0.56,0.589942,106,65,11,14

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,"(Regression Advanced, l1)",0.612245,0.269231,0.177215,0.56,0.589942,106,65,11,14

In [63]:
all_modify_results = []
for solver in ["liblinear", "lbfgs", "saga"]:
  method_name = "Regression Advanced", solver
  modelAdvanced = LogisticRegression(solver = solver, random_state=42, max_iter=1000, class_weight="balanced")
  result = evaluate_model(method_name, modelAdvanced, x_train, x_test, y_train, y_test)
  all_modify_results.append(result)
df_modify_results = pd.DataFrame(all_modify_results)
display(df_modify_results)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,"(Regression Advanced, liblinear)",0.637755,0.268041,0.180556,0.52,0.587485,112,59,12,13
1,"(Regression Advanced, lbfgs)",0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14
2,"(Regression Advanced, saga)",0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,"(Regression Advanced, liblinear)",0.637755,0.268041,0.180556,0.52,0.587485,112,59,12,13
1,"(Regression Advanced, lbfgs)",0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14
2,"(Regression Advanced, saga)",0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14

In [64]:
all_modify_results = []
for c in [0.01, 0.1, 1, 5, 10, 20, 50]:
  method_name = "Regression Advanced", c
  modelAdvanced = LogisticRegression(C = c, random_state=42, max_iter=1000, class_weight="balanced")
  result = evaluate_model(method_name, modelAdvanced, x_train, x_test, y_train, y_test)
  all_modify_results.append(result)
df_modify_results = pd.DataFrame(all_modify_results)
display(df_modify_results)

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,"(Regression Advanced, 0.01)",0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14
1,"(Regression Advanced, 0.1)",0.622449,0.274510,0.181818,0.56,0.595789,108,63,11,14
2,"(Regression Advanced, 1)",0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14
3,"(Regression Advanced, 5)",0.632653,0.250000,0.169014,0.48,0.567485,112,59,13,12
4,"(Regression Advanced, 10)",0.637755,0.252632,0.171429,0.48,0.570409,113,58,13,12
5,"(Regression Advanced, 20)",0.637755,0.252632,0.171429,0.48,0.570409,113,58,13,12
6,"(Regression Advanced, 50)",0.637755,0.252632,0.171429,0.48,0.570409,113,58,13,12

,Model,Accuracy,F1,Precision,Recall,ROC AUC,True Negative,False Positive,False Negative,True Positive
0,"(Regression Advanced, 0.01)",0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14
1,"(Regression Advanced, 0.1)",0.622449,0.274510,0.181818,0.56,0.595789,108,63,11,14
2,"(Regression Advanced, 1)",0.647959,0.288660,0.194444,0.56,0.610409,113,58,11,14
3,"(Regression Advanced, 5)",0.632653,0.250000,0.169014,0.48,0.567485,112,59,13,12
4,"(Regression Advanced, 10)",0.637755,0.252632,0.171429,0.48,0.570409,113,58,13,12
5,"(Regression Advanced, 20)",0.637755,0.252632,0.171429,0.48,0.570409,113,58,13,12
6,"(Regression Advanced, 50)",0.637755,0.252632,0.171429,0.48,0.570409,113,58,13,12

In [65]:
from sklearn.preprocessing import StandardScaler

def importance_variable_regression_model(modelName, model, X_train, X_test, Y_train, Y_test):
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  y_prob = model.predict_proba(X_test)[:, 1]
  importance = pd.DataFrame({
      "Feature": X_train.columns,
      "Coefficient": model.coef_[0]
  })

  display(importance)


def importance_variable_random_forest_model(modelName, model, X_train, X_test, Y_train, Y_test):
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  y_prob = model.predict_proba(X_test)[:, 1]
  importance = pd.DataFrame({
      "Feature": X_train.columns,
      "Importance": model.feature_importances_
  })

  display(importance)

In [66]:
importance_variable_regression_model("Regression", LogisticRegression(random_state=42, max_iter=1000, class_weight="balanced"), x_train, x_test, y_train, y_test)

                         Feature  Coefficient
0                   BEST PICTURE    -0.002848
1     INTERNATIONAL FEATURE FILM    -0.681483
2                      DIRECTING     1.886564
3        ACTOR IN A LEADING ROLE     0.379949
4      ACTRESS IN A LEADING ROLE    -0.134708
5     ACTOR IN A SUPPORTING ROLE     0.103643
6   ACTRESS IN A SUPPORTING ROLE    -0.553261
7   WRITING (Adapted Screenplay)    -0.017083
8       WRITING (Original Story)     0.083651
9          MUSIC (Original Song)    -0.738484
10        MUSIC (Original Score)    -0.412627
11                VISUAL EFFECTS     0.784538
12                 ART DIRECTION    -0.141998
13                  SOUND MIXING     0.563341
14                COSTUME DESIGN     0.394323
15             Total_Nominations     0.319891

                         Feature  Coefficient
0                   BEST PICTURE    -0.002848
1     INTERNATIONAL FEATURE FILM    -0.681483
2                      DIRECTING     1.886564
3        ACTOR IN A LEADING ROLE     0.379949
4      ACTRESS IN A LEADING ROLE    -0.134708
5     ACTOR IN A SUPPORTING ROLE     0.103643
6   ACTRESS IN A SUPPORTING ROLE    -0.553261
7   WRITING (Adapted Screenplay)    -0.017083
8       WRITING (Original Story)     0.083651
9          MUSIC (Original Song)    -0.738484
10        MUSIC (Original Score)    -0.412627
11                VISUAL EFFECTS     0.784538
12                 ART DIRECTION    -0.141998
13                  SOUND MIXING     0.563341
14                COSTUME DESIGN     0.394323
15             Total_Nominations     0.319891

In [67]:
importance_variable_random_forest_model("Random Forest", RandomForestClassifier(random_state=42, class_weight="balanced"), x_train, x_test, y_train, y_test)

                         Feature  Importance
0                   BEST PICTURE    0.000000
1     INTERNATIONAL FEATURE FILM    0.006815
2                      DIRECTING    0.147658
3        ACTOR IN A LEADING ROLE    0.065893
4      ACTRESS IN A LEADING ROLE    0.058345
5     ACTOR IN A SUPPORTING ROLE    0.059840
6   ACTRESS IN A SUPPORTING ROLE    0.044109
7   WRITING (Adapted Screenplay)    0.058500
8       WRITING (Original Story)    0.021996
9          MUSIC (Original Song)    0.017194
10        MUSIC (Original Score)    0.058417
11                VISUAL EFFECTS    0.034590
12                 ART DIRECTION    0.045467
13                  SOUND MIXING    0.077752
14                COSTUME DESIGN    0.041638
15             Total_Nominations    0.261785

                         Feature  Importance
0                   BEST PICTURE    0.000000
1     INTERNATIONAL FEATURE FILM    0.006815
2                      DIRECTING    0.147658
3        ACTOR IN A LEADING ROLE    0.065893
4      ACTRESS IN A LEADING ROLE    0.058345
5     ACTOR IN A SUPPORTING ROLE    0.059840
6   ACTRESS IN A SUPPORTING ROLE    0.044109
7   WRITING (Adapted Screenplay)    0.058500
8       WRITING (Original Story)    0.021996
9          MUSIC (Original Song)    0.017194
10        MUSIC (Original Score)    0.058417
11                VISUAL EFFECTS    0.034590
12                 ART DIRECTION    0.045467
13                  SOUND MIXING    0.077752
14                COSTUME DESIGN    0.041638
15             Total_Nominations    0.261785